# Generated by Django 3.0.6 on 2021-02-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='COURSE',
        ),
    ]
